[package]
name = "challenge"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
image = "0.25.6"

nokhwa = { version = "0.10", features = ["input-native", "output-wgpu"] }
